### PR TITLE
[darwin_embedded] Support TVOS and update ios for 64bit support

### PR DESCRIPTION
**Pull request by fuzzard**
Adds tvos platform build support
Adds ios 64bit build support

### CODE REVIEW

**Comment by garbear** [comment]
Does this look good? https://github.com/kodi-game/game.libretro.2048/commit/4d55fe39b0bd39d895a27fb8b207127360ae7c9d

**Comment by fuzzard** [comment]
Looks good except for my stuff-up, haha. Left an extra soname in tvos. I'll get that fixed up

**Comment by fuzzard** [comment]
Fixed the mistake up @garbear

**Comment by garbear** [comment]
great, thanks! I'll assume the rest is good and merge. when I get a chance I'll update all game add-ons

**Pull request merged**
