### PR TITLE
Set up CI with Azure Pipelines

### PR DESCRIPTION
**Pull request by garbear**
## Description

This PR adds an azure pipeline YML to run the `process_game_addons.py` script.

Template parameters are used to build each game add-on in a separate step. This lets CI logs display how much time individual add-ons took to build.

Currently, the script triggers on master. This should be changed to a cron job, possibly daily compiles and weekly pushes.

@AlwinEsch can we host it on a kodi azure account?

## How has this been tested?

The total build time is unknown, but probably several hours. When testing with my personal Azure account, I have to disable 1/3 of the cores to stay under the 1hr limit. Most cores are quick, with some  outliers:

* FBNeo: 6 mins
* MAME 2010: 12 mins
* MAME 2015: 25 mins
* MAME 2016: 43 mins
* MAME: times out after 1hr
* ScummVM: 22 mins

I enabled every core and triggered a run that will time out after 1hr: https://dev.azure.com/themagnificentmrb/kodi-game-scripting/_build/results?buildId=119&view=results

### CODE REVIEW

**Comment by AlwinEsch** [comment]
About the time out you can try to add `timeoutInMinutes: 360` (is the max for open source), see https://docs.microsoft.com/en-us/azure/devops/pipelines/process/phases?view=azure-devops&tabs=yaml&viewFallbackFrom=vsts#timeouts.

But not sure if that is enough by this amount of builds. Maybe we can increase more if we add a own build server to Azure.

**Comment by AlwinEsch** [comment]
About hosting is no problem, only if there before no file present want Azure to push a commit or to create a request about.
I can add also like on other by let Azure auto create a request and then linked also to here.

**Comment by garbear** [comment]
> About the time out you can try to add timeoutInMinutes: 360

I found `timeoutInMInutes: 0` will use the max (1 hr for private, 6hr for open source and unlimited on self-hosted). I added my 16-core server to azure, and it ran the pipeline for the 106 working add-ons (out of 114) in 2 hrs, 14 mins:

Result of the mega-run is here: https://dev.azure.com/themagnificentmrb/kodi-game-scripting/_build/results?buildId=203&view=results

I'll see if azure can build in less than 6 hours.

>  want Azure to push a commit or to create a request about

Creating a pull request would be better. Can you help with this?

**Comment by AlwinEsch** [comment]
Have connected Azure to the addon with https://github.com/kodi-game/kodi-game-scripting/pull/82, after them here is in I close the request.

**Comment by AlwinEsch** [comment]
How was my commit landed in your request? Stupid circumstance that this request type was already there :thinking:?

**Comment by garbear** [comment]
Not in my pull request, your [commit](https://github.com/kodi-game/kodi-game-scripting/commit/966b4a604e1cb36b008524ad0632755082ce1dff) has the text #79 in it, so this PR just links back to it and appears here.

Thanks for the graffiti :wink:

**Comment by garbear** [comment]
I got ppsspp working. I also disabled MAME to fit within the 6 hour time limit. Latest run: https://dev.azure.com/themagnificentmrb/kodi-game-scripting/_build/results?buildId=237&view=results

Time results:

* Without MAME: 4 hrs, 7 mins
* Just MAME ([log](https://dev.azure.com/themagnificentmrb/kodi-game-scripting/_build/results?buildId=215)): 2 hrs, 50 mins

**Comment by AlwinEsch** [comment]
> Not in my pull request, your commit has the text #79 in it, so this PR just links back to it and appears here.

Ups, SORRY! Yeah if there is a link inside commit comes a reference on his place. Crazy was that his view here looks like a inserted commit (only that point before is missing :sweat_smile:).

**Pull request merged**
