### PR TITLE
[master] metadata sync action

### PR DESCRIPTION
**Pull request by gade01**
This action will automatically sync:
- Summary
- Description
- Disclaimer  

between addon.xml and language files.

When changes are done in either addon.xml or in the language files, the action will open a pull request with the synced changes.

Please merge any open Weblate pull request first.

### CODE REVIEW

**Comment by garbear** [comment]
Looks great! I don't think we need PRs on every single change (doesn't scale with 125 add-ons). Can you have the workflow push directly?

**Comment by gade01** [comment]
I'll hear @anxdpanic if that's possible.
He coded the script and workflow.

**Comment by gade01** [comment]
@garbear 
Thanks to @anxdpanic this action will now push directly.
We should probably change the actions for other repos to do the same.

Should we still keep `if settings`?

**Comment by garbear** [comment]
We should drop `if settings`. And we might need to modify the templates folder or even the code to always generate a language file.

Another concern is that we regex-replace the "Supported files" line in the generated description: [`{% if ("Supported files: " in xml.addon.extension[1].description.content) %}`](https://github.com/kodi-game/kodi-game-scripting/blob/076b9198dbf52b3111aab2ac3e790b6949a0d4c7/templates/addon/%7B%7B%20game.addon%20%7D%7D/addon.xml.in.j2#L33). The extra languages might mess with the parsing. Once we get this PR ready, let's test on an add-on.

**Comment by gade01** [comment]
Exactly, I agree on always generate a language file for translations of addon.xml.

I removed `if settings`.

**Comment by garbear** [comment]
@gade01 I've been waiting to test the generator on multiple &lt;description> tags. It parses for supported extensions to generate a new description (which would clear the translation), and multiple &lt;description> tags for different languages in addon.xml might interfere.

Regrettably, I have no time to test. What do you think? I want to bump all add-ons for the language changes, and I'm eagerly willing to risk a few hundred extra builds on the mirrors.

**Comment by gade01** [comment]
@garbear 
Lets's try it out and see what happens. :)
I have time right now to test and fix stuff if anything happens.

**Comment by garbear** [comment]
I'm doing a full run of add-ons. Let's see how this goes!

**Pull request merged**
