### PR TITLE
Update mingw to version 2023-10-26

### PR DESCRIPTION
**Pull request by garbear**
## Description

Current mingw on the mirrors, version 2021-07-25, tries to hit some URLs for packages that no longer resolve properly. I tried updating msys2 to the latest version, and cores now build successfully.

## How has this been tested?

Tested with genplus: https://jenkins.kodi.tv/blue/organizations/jenkins/kodi-game%2Fgame.libretro.genplus/detail/testing/5/pipeline/13/

### CODE REVIEW

**Comment by CrystalP** [comment]
Please align with what will happen in #24133, to point to msys2 mirrors or our own.

**Comment by garbear** [comment]
OK, will do

**Comment by garbear** [comment]
I've updated the PR. We now pull msys2 from our mirrors, saving ~50MB (times 2 for win32/64) of download from hitting the msys2 mirrors on each add-on build.

The next step would be something like this change: https://github.com/kodi-game/kodi-game-scripting/commit/temp-mingw. It also pulls the individual packages from our mirrors.

In order for that to work, we'd need to upload the following packages for win64:

```
mingw-w64-x86_64-binutils-2.41-2
mingw-w64-x86_64-crt-git-11.0.0.r239.g037ba0184-1
mingw-w64-x86_64-gcc-libs-13.2.0-2
mingw-w64-x86_64-gmp-6.3.0-2
mingw-w64-x86_64-headers-git-11.0.0.r239.g037ba0184-1
mingw-w64-x86_64-isl-0.26-1
mingw-w64-x86_64-libiconv-1.17-3
mingw-w64-x86_64-libwinpthread-git-11.0.0.r239.g037ba0184-1
mingw-w64-x86_64-mpc-1.3.1-2
mingw-w64-x86_64-mpfr-4.2.1-2
mingw-w64-x86_64-windows-default-manifest-6.4-4
mingw-w64-x86_64-winpthreads-git-11.0.0.r239.g037ba0184-1
mingw-w64-x86_64-zlib-1.3-1
mingw-w64-x86_64-zstd-1.5.5-1
make-4.4.1-1
mingw-w64-x86_64-gcc-13.2.0-2
```

And the following packages for win32:

```
mingw-w64-i686-binutils-2.41-2
mingw-w64-i686-crt-git-11.0.0.r239.g037ba0184-1
mingw-w64-i686-gcc-libs-13.2.0-2
mingw-w64-i686-gmp-6.3.0-2
mingw-w64-i686-headers-git-11.0.0.r239.g037ba0184-1
mingw-w64-i686-isl-0.26-1
mingw-w64-i686-libiconv-1.17-3
mingw-w64-i686-libwinpthread-git-11.0.0.r239.g037ba0184-1
mingw-w64-i686-mpc-1.3.1-2
mingw-w64-i686-mpfr-4.2.1-2
mingw-w64-i686-windows-default-manifest-6.4-4
mingw-w64-i686-winpthreads-git-11.0.0.r239.g037ba0184-1
mingw-w64-i686-zlib-1.3-1
mingw-w64-i686-zstd-1.5.5-1
make-4.4.1-1
mingw-w64-i686-gcc-13.2.0-2
```

**Comment by garbear** [comment]
Looks like this now works for 2048: https://jenkins.kodi.tv/blue/organizations/jenkins/kodi-game%2Fgame.libretro.2048/detail/1.0.0.139-Nexus/1/pipeline

**Pull request merged**
